config/routes.rb
Mobile::Application.routes.draw do
  resources :notes
  
  match 'app/views/notes/index.html.erb' => 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, :notice => 'Note was successfully created.' }
        format.json { render :json => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, :notice => 'Note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page">
  
  <div data-role="header">
    <div data-role="navbar">
      <ul>
          <li><%= link_to "Alle Notizen",notes_path %></li>
          <li><%= link_to "Neue Notiz",new_note_path %></li>
      </ul>
    </div>
  </div>
  
  <div data-role="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <div data-role="controlgroup" data-type="horizontal" data-iconpos="left" >
        <%= link_to "Back", notes_path,"data-role"=>"button","data-icon"=>"arrow-l" %>
        <%= f.submit "data-icon"=>"plus" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<% @notes.each do |note| %>
    <ul data-role="listview" data-inset="true" data-theme="c" data-split-icon="gear">
      <li data-role="list-divider">Deine Notizen</li>
        <li><%= link_to note.title,note_path(note)%>
          <%= link_to 'Edit', edit_note_path(note) %>
        </li>
    </ul>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Description:</b>
  <%= @note.description %>
</p>

<div data-role="controlgroup" data-type="horizontal" data-iconpos="left" >
        <%= link_to "Back", notes_path,"data-role"=>"button","data-icon"=>"arrow-l" %>
        <%= link_to "Destroy", note_path(@note),:method=>:delete,:confirm=>"Sicher?","data-role"=>"button","data-icon"=>"arrow-l" %>
</div>